package NewLanguage.sandbox;

/*Generated by MPS */


public class map_App {
  public static void main(String[] args) {
    System.out.println("//Code generated by ArduinoML");
    System.out.println("void setup() {");
    System.out.println("pinMode(" + 12 + ", OUTPUT);");
    System.out.println(" pinMode(" + 9 + ", INPUT);");
    System.out.println("pinMode(" + 11 + ", OUTPUT);");
    System.out.println("}");
  }
}
