package NewLanguage.sandbox;

/*Generated by MPS */


public class map_App {
  public static void main(String[] args) {
    System.out.println("//Code generated by ArduinoML");
    System.out.println("//Structural concepts");
    System.out.println("void setup() {");
    System.out.println("pinMode(" + 12 + ", OUTPUT);");
    System.out.println(" pinMode(" + 9 + ", INPUT);");
    System.out.println("}");
    System.out.println("\n//Behavioral concepts");
    System.out.println("long time = 0; long debounce = 200;\n");
    System.out.println("//Here comes states declarations");
    System.out.println("\nvoid loop() { state_" + "off" + "(); } //Entering init state\n");
  }
}
